### ISSUE TITLE
Fix API Connection So It doesn't get stuck on Downloaded Needed Data

### ISSUE THREAD

**Issue by Starman10** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#11]
![image](https://user-images.githubusercontent.com/6334208/95689743-bd76a980-0bc7-11eb-96f8-39e351bdaa0f.png)

The application fails to install due to a broken API link according to https://www.reddit.com/r/uwuvci/comments/j69u3y/it_keeps_getting_stuck_at_this_screen_whenever_i/

I am also experiencing this issue.

**Comment by Hotbrawl20** [comment]
As the creator of said commit i am already informed on this issue. i will work on  a fix soonish. Expect an update in the next few days
