### ISSUE TITLE
convert error?

### ISSUE THREAD

**Issue by xUnleqitTV** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#25]
hey i've used UWUVCI to create the WUP files to inject Wii Sports + Wii Sports Resort in the Virtual Console this worked fine i can install the game via WUP Installer GX2 but when i start the Game the wii u tells me i have to install the game new in the e-shop because some files are broken.

**Comment by ZestyTS** [comment]
Are you able to make other Wii games? And have you tested that your rip works, maybe via Dolphin? Once you're able to confirm then that'll remove enough of the variables for us to test and see what happened.

**Comment by ZestyTS** [comment]
Gotcha, yeah it should work, thanks.
![image](https://user-images.githubusercontent.com/1396621/172938475-138efa50-357b-4d1f-9ddd-dc105a16e054.png)
@NicoAICP
