### ISSUE TITLE
FTP connection failed

### ISSUE THREAD

**Issue by DinuNuggets** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#41]
With the vwii theme injection I entered everything correctly and even my wiiu says that a connection was attempted.

But I get FTP connection failed all the time

**Comment by NicoAICP** [comment]
Please do me a favour of closing this issue and reopening it here:
https://github.com/stuff-by-3-random-dudes/UWUVCI-VWII

Please also include what ftp server you used on the wiiu
