### ISSUE TITLE
Stuck in "Downloading Tools" screen at first launch

### ISSUE THREAD

**Issue by ElectableRuby31** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#51]
Welp I used the downloader, and it worked great, but when I first launched the program, the progress bar started moving until a certain point and then seemed to stop and didn't seem to move. When I relaunch the app, the bar restarts but gets stuck in the same point.
![image](https://user-images.githubusercontent.com/81558780/202850308-6ae51c90-e593-47f9-8f39-30c90a08bd3d.png)

**Comment by ZestyTS** [comment]
Delete the tools folder and try again.

**Comment by ElectableRuby31** [comment]
worked! thanks!
