### ISSUE TITLE
Crash when clicking on Yes for the Wii boot image

### ISSUE THREAD

**Issue by Tom60chat** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#52]
![Screenshot](https://user-images.githubusercontent.com/25564492/208938951-00c19a38-b0c1-4949-8e87-c3b347bc75f1.png)

After closing the weird unknown ROM message, if I click yes the application crash.

## Windows crash report :
Description: the process has been stopped due to an unhandled exception.
Information about the exception : System.UnauthorizedAccessException
   à System.IO.Directory.DeleteHelper(System.String, System.String, Boolean, Boolean, WIN32_FIND_DATA ByRef)
   à System.IO.Directory.Delete(System.String, System.String, Boolean, Boolean)
   à System.IO.Directory.Delete(System.String, Boolean)
   à UWUVCI_AIO_WPF.UI.Windows.IMG_Message.Yes_Click(System.Object, System.Windows.RoutedEventArgs)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   à System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   à System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   à System.Windows.Controls.Primitives.ButtonBase.OnClick()
   à System.Windows.Controls.Button.OnClick()
   à System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   à System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   à System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   à System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   à System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   à System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   à System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   à System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   à System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   à System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   à System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   à System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   à System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   à System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   à System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   à System.Windows.Application.RunDispatcher(System.Object)
   à System.Windows.Application.RunInternal(System.Windows.Window)
   à System.Windows.Application.Run(System.Windows.Window)
   à UWUVCI_AIO_WPF.App.Main()

## Work around:
Start as administrator (the weird message disappears, and the Yes button no longer crashes the application).

**Comment by ZestyTS** [comment]
The error message is saying that it doesn't like the game you are using. I'm assuming the rom is something that isn't just a straight iso.  I would suggest to not use a compressed version next time.

**Comment by ZestyTS** [comment]
Without knowing about what rom you're using, and knowing that admin rights is required, this is working as intended.

**Comment by Tom60chat** [comment]
If admin is required, maybe warn the user is in user mode and ask him to start as admin ?
I never see a app saying a crash is working as intended...

**Comment by NicoAICP** [comment]
It seems the Location the application is installed to or tries to access is locked behind admin rights -> thus throwing the unauthorized exception.
Normal usage does not require admin rights, thus the comment that it is working as intended.

I would recommend you to maybe try and install the tool in the documents folder (even tho that seems wierd in a normal use case), since this would not require admin rights to use the tool

**Comment by NicoAICP** [comment]
Since its using that Inno Setup installer it doesnt check IIRC, thats why i recommend the documents folder (which was the normal install location in the beta, caused some issues for paralel users, thats why that was changed
