### ISSUE TITLE
Site for compatibility missing item

### ISSUE THREAD

**Issue by SwirlyStone5877** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#54]
Your site for compatibility (https://flumpster.github.io/instructions/index) is missing an item in the N64 list (https://flumpster.github.io/instructions/n64/compat-n64.html). 

Game name: Super Spamton 64 (mod of Super Mario 64)
Region: USA/EUR (Depends on Patched Base Super Mario 64 mod)
Host Game: Not Donkey Kong 64 US (for my ROM), about to try Donkey Kong 64 EU (again, for my ROM)
Status: ?
Notes: ?

Will update soon once tested.

**Comment by SwirlyStone5877** [comment]
Update:

Host Game: Not Donkey Kong 64 EU or US (for my ROM), about to try 1080° Snowboarding US
Status: Doesn't work
Notes: Black screen, doesn't launch at all (same problem for US)

**Comment by SwirlyStone5877** [comment]
Update:

Host Game: Not DK64 EU or US, and not 1080° Snowboarding US, about to try Excitebike 64 US
Status: Doesn't work
Notes: Same problem as others

**Comment by SwirlyStone5877** [comment]
Update:

Host Game: Not DK64 EU or US, 1080° Snowboarding US, or Excitebike 64 US, about to try F-Zero X US
Status: Doesn't work
Notes: Same problem as others

**Comment by ZestyTS** [comment]
This is for the desktop app itself, not the website.
The website repo can be found here
https://github.com/[Flumpster/flumpster.github.io](https://github.com/Flumpster/flumpster.github.io)

**Comment by SwirlyStone5877** [comment]
oh
