### ISSUE TITLE
Could not find part of the path C:\Users\Jofren\OneDrive\Desktop\Documents\UWUVCI AIO\bin\temp\TEMP

### ISSUE THREAD

**Issue by LoreMF** [stuff-by-3-random-dudes/UWUVCI-AIO-WPF#66]
I have the Lego Lord of the Rings iso using rhythm heaven feaver as a base.  However, when I go to inject I get the error: Injection Failed due to unknown circumstances, please contact us on the UWUVCI discord

 Don't forget that there's an FAQ in the ReadMe.txt file and on the UWUVCI Discord

 Error Message:

 Could not find part of the path C:\Users\Jofren\OneDrive\Desktop\Documents\UWUVCI AIO\bin\temp\TEMP.

**Comment by ZestyTS** [comment]
You wrote this originally on the video guide, and when I replied I noticed you deleted your comment. Anyway, as the error message says, open up the Readme file and look at number 28.
